### ISSUE TITLE
AccountNotFound

### ISSUE THREAD

**Issue by mdstevens044** [CalebEverett/metaplex-cli#3]
No matter what command I run I get 
```AccountNotFound: pubkey=9W6gByZVnd9MTRTQDba2aUkcPPgdM3Fs7iwegQWiky8L```
Not sure where this pubkey is coming from but it is not mine

**Comment by CalebEverett** [comment]
Hi, what system are you running on windows, mac or linux? That is a strange one and that address isn't anywhere in the code, but if you can give me a bit more information, I can try to track it down.

**Comment by CalebEverett** [comment]
Closing with no response. Feel free to leave another comment if this still needs to be resolved.
